# -*- ruby -*-
require 'rubygems'
require 'rake/testtask'

task :default => :test

desc "Run basic tests"
Rake::TestTask.new { |t|
  t.pattern = 'test/test_*.rb'
  t.verbose = true
  t.warning = true
}



# vim: syntax=Ruby
